version: '3'

services:

  # https://hub.docker.com/_/php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    networks:
      - appnet

  # https://hub.docker.com/_/nginx
  # https://laravel.com/docs/7.x/deployment#nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - php
      - mysql
    ports:
     - 80:80
    volumes:
     - ./src:/var/www/html:cached
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
     - appnet

  # https://hub.docker.com/_/mysql
  # https://laravel.com/docs/7.x/database
  mysql:
    image: mysql:5.7
    container_name: ${DB_HOST}
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    networks:
      - appnet

  # https://hub.docker.com/_/redis
  # https://laravel.com/docs/7.x/redis
  redis:
    image: redis:alpine
    container_name: redis
    networks:
     - appnet

# https://docs.docker.com/network/
networks:
  appnet:
    driver: bridge
